name: adhunter
channels:
  - conda-forge/label/cf201901
  - bioconda
  - defaults
  - conda-forge
dependencies:
  - absl-py=1.4.0
  - aiohttp=3.8.4
  - aiosignal=1.3.1
  - alsa-lib=1.2.8
  - async-timeout=4.0.2
  - attr=2.5.1
  - attrs=23.1.0
  - backcall=0.2.0
  - backports=1.1
  - backports.zoneinfo=0.2.1
  - blinker=1.6.2
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.19.0
  - cairo=1.16.0
  - cffi=1.15.1
  - charset-normalizer=2.1.1
  - click=8.1.3
  - colorama=0.4.6
  - contourpy=1.0.7
  - cryptography=40.0.2
  - cudatoolkit=10.1.243
  - cycler=0.11.0
  - dbus=1.13.6
  - decorator=5.1.1
  - diamond=0.9.14
  - dnachisel=3.2.11
  - docopt=0.6.2
  - expat=2.5.0
  - filelock=3.12.0
  - flametree=0.1.11
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.39.4
  - freetype=2.12.1
  - frozenlist=1.3.3
  - fsspec=2023.5.0
  - gettext=0.21.1
  - glib=2.76.2
  - glib-tools=2.76.2
  - google-auth-oauthlib=1.0.0
  - graphite2=1.3.13
  - grpcio=1.54.2
  - gst-plugins-base=1.22.0
  - gstreamer=1.22.0
  - harfbuzz=7.3.0
  - icu=72.1
  - idna=3.4
  - importlib-metadata=6.6.0
  - importlib-resources=5.12.0
  - importlib_resources=5.12.0
  - ipywidgets=8.1.5
  - jinja2=3.1.2
  - joblib=1.2.0
  - jupyterlab_widgets=3.0.13
  - keyutils=1.6.1
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.15
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20230125.2
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcap=2.67
  - libcblas=3.9.0
  - libclang13=16.0.3
  - libcups=2.3.3
  - libdeflate=1.18
  - libedit=3.1.20191231
  - libevent=2.1.12
  - libexpat=2.5.0
  - libffi=3.4.2
  - libflac=1.4.2
  - libgcc-ng=12.2.0
  - libgcrypt=1.10.1
  - libgfortran-ng=12.2.0
  - libgfortran5=12.2.0
  - libglib=2.76.2
  - libgpg-error=1.46
  - libgrpc=1.54.2
  - libhwloc=2.9.1
  - libiconv=1.17
  - libjpeg-turbo=2.1.5.1
  - liblapack=3.9.0
  - libllvm16=16.0.3
  - libnsl=2.0.0
  - libogg=1.3.4
  - libopenblas=0.3.21
  - libopus=1.3.1
  - libpng=1.6.39
  - libpq=15.3
  - libprotobuf=3.21.12
  - libsndfile=1.2.0
  - libsqlite=3.42.0
  - libstdcxx-ng=12.2.0
  - libsystemd0=253
  - libtiff=4.5.0
  - libuuid=2.38.1
  - libuv=1.44.2
  - libvorbis=1.3.7
  - libwebp-base=1.3.0
  - libxcb=1.13
  - libxkbcommon=1.5.0
  - libxml2=2.10.4
  - libzlib=1.2.13
  - llvm-openmp=16.0.4
  - lz4-c=1.9.4
  - markdown=3.4.3
  - markupsafe=2.1.2
  - matplotlib=3.7.1
  - matplotlib-base=3.7.1
  - mkl=2022.2.1
  - mpg123=1.31.3
  - mpmath=1.3.0
  - multidict=6.0.4
  - munkres=1.1.4
  - mysql-common=8.0.32
  - mysql-libs=8.0.32
  - natsort=5.5.0
  - ncurses=6.3
  - networkx=3.1
  - nspr=4.35
  - nss=3.89
  - oauthlib=3.2.2
  - openblas=0.3.21
  - openjpeg=2.5.0
  - packaging=23.1
  - pandas=2.0.1
  - patsy=0.5.3
  - pcre2=10.40
  - pickleshare=0.7.5
  - pillow=9.5.0
  - pip=23.1.2
  - pixman=0.40.0
  - platformdirs=3.5.1
  - ply=3.11
  - polars=0.20.2
  - pooch=1.7.0
  - proglog=0.1.9
  - prompt_toolkit=3.0.48
  - protobuf=4.21.12
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pulseaudio-client=16.1
  - pure_eval=0.2.3
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.21
  - pydeprecate=0.3.2
  - pyjwt=2.7.0
  - pyopenssl=23.1.1
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pysocks=1.7.1
  - python=3.8.16
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - python_abi=3.8
  - pytorch-lightning=1.7.7
  - pytz=2023.3
  - pyu2f=0.1.5
  - pyyaml=6.0
  - qt-main=5.15.8
  - re2=2023.03.02
  - readline=8.2
  - requests=2.29.0
  - requests-oauthlib=1.3.1
  - rsa=4.9
  - scipy=1.10.1
  - seaborn=0.12.2
  - seaborn-base=0.12.2
  - setuptools=67.7.2
  - sip=6.7.9
  - six=1.16.0
  - sleef=3.5.1
  - stack_data=0.6.2
  - statsmodels=0.14.0
  - sympy=1.12
  - tbb=2021.9.0
  - tensorboard=2.13.0
  - tensorboard-data-server=0.7.0
  - threadpoolctl=3.1.0
  - tk=8.6.12
  - toml=0.10.2
  - tomli=2.0.1
  - torchmetrics=0.11.4
  - torchvision=0.15.2
  - tornado=6.3.2
  - tqdm=4.65.0
  - typing-extensions=4.5.0
  - typing_extensions=4.5.0
  - tzdata=2023c
  - unicodedata2=15.0.0
  - urllib3=1.26.15
  - werkzeug=2.3.4
  - wheel=0.40.0
  - widgetsnbextension=4.0.13
  - xcb-util=0.4.0
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.0
  - xcb-util-renderutil=0.3.9
  - xcb-util-wm=0.4.1
  - xkeyboard-config=2.38
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.8.4
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xf86vidmodeproto=2.3.1
  - xorg-xproto=7.0.31
  - xz=5.2.6
  - yaml=0.2.5
  - yarl=1.9.1
  - zipp=3.15.0
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
      - alabaster==0.7.13
      - alembic==1.12.1
      - asttokens==2.2.1
      - astunparse==1.6.3
      - babel==2.16.0
      - beautifulsoup4==4.13.4
      - biopython==1.81
      - blessed==1.20.0
      - bottle==0.13.4
      - cachetools==4.2.4
      - captum==0.7.0
      - chemprop==1.7.1
      - cloudpickle==3.0.0
      - cmake==3.27.7
      - codon-harmony==1.0.0
      - colorlog==6.7.0
      - comm==0.1.3
      - debugpy==1.6.7
      - descriptastorus==2.6.1
      - docstring-parser==0.16
      - docutils==0.20.1
      - epitopepredict==0.5.0
      - et-xmlfile==1.1.0
      - ete3==3.1.3
      - executing==1.2.0
      - fair-esm==2.0.0
      - fastaparser==1.1.1
      - fastcluster==1.2.6
      - fastjsonschema==2.21.1
      - flask==2.1.3
      - flatbuffers==24.3.25
      - future==0.18.3
      - gast==0.3.3
      - google-auth==2.28.2
      - google-pasta==0.2.0
      - gpustat==1.1.1
      - greenlet==3.0.1
      - h5py==2.10.0
      - hyperopt==0.2.7
      - imagesize==1.4.1
      - imbalanced-learn==0.12.4
      - imblearn==0.0
      - ipykernel==6.23.1
      - ipython==8.12.2
      - itsdangerous==2.2.0
      - jedi==0.18.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - jupyter-client==8.2.0
      - jupyter-core==5.3.0
      - keras==2.13.1
      - keras-preprocessing==1.1.2
      - lazypredict==0.2.12
      - levenshtein==0.25.1
      - libclang==18.1.1
      - lightgbm==4.5.0
      - lit==17.0.4
      - llvmlite==0.41.1
      - lmdb==1.5.1
      - mako==1.2.4
      - matplotlib-inline==0.1.6
      - matplotlib-venn==0.11.9
      - mypy-extensions==1.0.0
      - nbformat==5.10.4
      - nest-asyncio==1.5.6
      - ninja==1.11.1.1
      - numba==0.58.1
      - numpy==1.24.4
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-ml-py==12.535.161
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nccl-cu12==2.23.4
      - nvidia-nvtx-cu11==11.7.91
      - nvitop==1.3.2
      - openpyxl==3.1.2
      - opentsne==1.0.1
      - opt-einsum==3.3.0
      - optuna==3.4.0
      - optuna-dashboard==0.19.0
      - pandas-flavor==0.6.0
      - parso==0.8.3
      - pexpect==4.8.0
      - pkgutil-resolve-name==1.3.10
      - plotly==5.18.0
      - prompt-toolkit==3.0.38
      - psutil==5.9.5
      - pure-eval==0.2.2
      - py4j==0.10.9.7
      - pygments==2.15.1
      - python-codon-tables==0.1.12
      - pyzmq==25.0.2
      - rapidfuzz==3.9.7
      - rdkit==2024.3.5
      - rdkit-pypi==2022.9.5
      - referencing==0.35.1
      - rpds-py==0.20.1
      - scikit-learn==1.3.2
      - sequence-models==1.8.0
      - shap==0.44.1
      - slicer==0.0.7
      - snowballstemmer==2.2.0
      - soupsieve==2.7
      - spectrae==1.0.3
      - sphinx==7.1.2
      - sphinx-rtd-theme==2.0.0
      - sphinxcontrib-applehelp==1.0.4
      - sphinxcontrib-devhelp==1.0.2
      - sphinxcontrib-htmlhelp==2.0.1
      - sphinxcontrib-jquery==4.1
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==1.0.3
      - sphinxcontrib-serializinghtml==1.1.5
      - sqlalchemy==2.0.23
      - statannotations==0.7.2
      - tenacity==8.2.3
      - tensorboard-plugin-wit==1.8.1
      - tensorboardx==2.6.2.2
      - tensorflow-estimator==2.13.0
      - tensorflow-io-gcs-filesystem==0.34.0
      - termcolor==2.4.0
      - torch==2.0.0
      - torchaudio==2.0.1
      - traitlets==5.9.0
      - triton==2.0.0
      - typed-argument-parser==1.10.1
      - typing-inspect==0.9.0
      - venn==0.1.3
      - wcwidth==0.2.6
      - wrapt==1.16.0
      - xarray==2023.1.0
      - xgboost==2.1.1